src/Entity/Address.php
<?php

namespace App\Entity;

use App\Repository\AddressRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AddressRepository::class)]
class Address
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[ORM\Column(length: 10)]
    private ?string $PostalCode = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    /**
     * @var Collection<int, Dates>
     */
    #[ORM\OneToMany(targetEntity: Dates::class, mappedBy: 'Address')]
    private Collection $dates;

    #[ORM\ManyToOne(inversedBy: 'addresses')]
    private ?Customer $customer = null;

    /**
     * @var Collection<int, Dates>
     */
    #[ORM\OneToMany(targetEntity: Dates::class, mappedBy: 'address')]
    private Collection $Dates;

    public function __construct()
    {
        $this->dates = new ArrayCollection();
        $this->Dates = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->PostalCode;
    }

    public function setPostalCode(string $PostalCode): static
    {
        $this->PostalCode = $PostalCode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    /**
     * @return Collection<int, Dates>
     */
    public function getDates(): Collection
    {
        return $this->dates;
    }

    public function addDate(Dates $date): static
    {
        if (!$this->dates->contains($date)) {
            $this->dates->add($date);
            $date->setAddress($this);
        }

        return $this;
    }

    public function removeDate(Dates $date): static
    {
        if ($this->dates->removeElement($date)) {
            // set the owning side to null (unless already changed)
            if ($date->getAddress() === $this) {
                $date->setAddress(null);
            }
        }

        return $this;
    }

    public function getCustomer(): ?Customer
    {
        return $this->customer;
    }

    public function setCustomer(?Customer $customer): static
    {
        $this->customer = $customer;

        return $this;
    }

    public function __toString(): string
    {
        return sprintf('%s (%s)', $this->getAddress(), $this->getPostalCode());
    }
}

src/Entity/Customer.php
<?php

namespace App\Entity;

use App\Repository\CustomerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CustomerRepository::class)]
class Customer extends Account
{
    /**
     * @var Collection<int, Request>
     */
    #[ORM\OneToMany(targetEntity: Request::class, mappedBy: 'client')]
    private Collection $requests;

    /**
     * @var Collection<int, Address>
     */
    #[ORM\OneToMany(targetEntity: Address::class, mappedBy: 'customer')]
    private Collection $addresses;

    /**
     * @var Collection<int, OrderHistory>
     */
    #[ORM\OneToMany(targetEntity: OrderHistory::class, mappedBy: 'Customer')]
    private Collection $orderHistories;

    public function __construct()
    {
        $this->requests = new ArrayCollection();
        $this->addresses = new ArrayCollection();
        $this->orderHistories = new ArrayCollection();
    }

    /**
     * @return Collection<int, Request>
     */
    public function getRequests(): Collection
    {
        return $this->requests;
    }

    public function addRequest(Request $request): static
    {
        if (!$this->requests->contains($request)) {
            $this->requests->add($request);
            $request->setClient($this);
        }

        return $this;
    }

    public function removeRequest(Request $request): static
    {
        if ($this->requests->removeElement($request)) {
            // set the owning side to null (unless already changed)
            if ($request->getClient() === $this) {
                $request->setClient(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Address>
     */
    public function getAddresses(): Collection
    {
        return $this->addresses;
    }

    public function addAddress(Address $address): static
    {
        if (!$this->addresses->contains($address)) {
            $this->addresses->add($address);
            $address->setCustomer($this);
        }

        return $this;
    }

    public function removeAddress(Address $address): static
    {
        if ($this->addresses->removeElement($address)) {
            // set the owning side to null (unless already changed)
            if ($address->getCustomer() === $this) {
                $address->setCustomer(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, OrderHistory>
     */
    public function getOrderHistories(): Collection
    {
        return $this->orderHistories;
    }

    public function addOrderHistory(OrderHistory $orderHistory): static
    {
        if (!$this->orderHistories->contains($orderHistory)) {
            $this->orderHistories->add($orderHistory);
            $orderHistory->setCustomer($this);
        }

        return $this;
    }

    public function removeOrderHistory(OrderHistory $orderHistory): static
    {
        if ($this->orderHistories->removeElement($orderHistory)) {
            // set the owning side to null (unless already changed)
            if ($orderHistory->getCustomer() === $this) {
                $orderHistory->setCustomer(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\InheritanceType("JOINED")]
#[ORM\DiscriminatorColumn("role_type", "string")]
#[ORM\DiscriminatorMap(["client" => Customer::class, "prestataire" => Provider::class, "administrateur" => Admin::class])]
abstract class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $Surname = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 20)]
    private ?string $phone = null;

    #[ORM\Column(length: 255)]
    private ?string $password = null;

    private string $plainPassword = '';

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $resetPasswordToken = null;

    #[ORM\Column(nullable: true)]
    private ?\DateTimeImmutable $resetTokenExpireAt = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->Surname;
    }

    public function setSurname(string $Surname): static
    {
        $this->Surname = $Surname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    public function eraseCredentials(): void
    {
        $this->plainPassword = '';
    }

    public function getUserIdentifier(): string
    {
        return $this->email;
    }

    public function getRoles(): array
    {
        return $this->roles;
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    public function setPlainPassword(string $plainPassword): void
    {
        $this->plainPassword = $plainPassword;
    }

    public function getPlainPassword(): string
    {
        return $this->plainPassword;
    }

    public function getResetPasswordToken(): ?string
    {
        return $this->resetPasswordToken;
    }

    public function setResetPasswordToken(?string $resetPasswordToken): static
    {
        $this->resetPasswordToken = $resetPasswordToken;

        return $this;
    }

    public function getResetTokenExpireAt(): ?\DateTimeImmutable
    {
        return $this->resetTokenExpireAt;
    }

    public function setResetTokenExpireAt(?\DateTimeImmutable $resetTokenExpireAt): static
    {
        $this->resetTokenExpireAt = $resetTokenExpireAt;

        return $this;
    }
}

src/Controller/CustomerController.php
<?php

namespace App\Controller;

use App\Entity\Admin;
use App\Entity\Customer;
use App\Entity\Account;
use App\Entity\Provider;
use App\Form\AddressType;
use App\Form\EditAdminType;
use App\Form\EditCustomerType;
use App\Form\EditProviderType;
use App\Form\RegistrationCustomerType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Security\Http\Attribute\IsGranted;

class CustomerController extends AbstractController
{
    #[Route('/{id}/profil', name: 'app_profil', methods: ['GET', 'POST'])]
    public function index(Request $request, Account $user, EntityManagerInterface $entityManager): Response
    {
        $this->denyAccessUnlessGranted('profil_zone');

        // Gestion du profil pour un utilisateur (Customer)
        if ($user instanceof Customer) {
            $formCustomer = $this->createForm(EditCustomerType::class, $user);
            $formCustomer->handleRequest($request);

            if ($formCustomer->isSubmitted() && $formCustomer->isValid()) {
                foreach ($user->getAddresses() as $address) {
                    if ($address->getId() === null) {
                        $address->setCustomer($user);
                        $entityManager->persist($address);
                    }
                }
                $user->setRoles(['ROLE_USER']);
                $entityManager->persist($user);
                $entityManager->flush();

                $this->addFlash('success', 'Modification du profil effectuée avec succès !');
            }

            return $this->render('customer/profil.html.twig', [
                'formCustomer' => $formCustomer,
                'customer' => $user,
            ]);
        }

        // Gestion du profil pour un prestataire (Provider)
        if ($user instanceof Provider) {
            $formProvider = $this->createForm(EditProviderType::class, $user);
            $formProvider->handleRequest($request);

            if ($formProvider->isSubmitted() && $formProvider->isValid()) {
                $user->setRoles(['ROLE_PRESTA']);
                $entityManager->persist($user);
                $entityManager->flush();

                $this->addFlash('success', 'Modification du profil effectuée avec succès !');
            }

            return $this->render('provider/profil.html.twig', [
                'formProvider' => $formProvider,
                'provider' => $user,
            ]);
        }

        // Gestion du profil pour un administrateur (Admin)
        if ($user instanceof Admin) {
            $formAdmin = $this->createForm(EditAdminType::class, $user);
            $formAdmin->handleRequest($request);

            if ($formAdmin->isSubmitted() && $formAdmin->isValid()) {
                $user->setRoles(['ROLE_ADMIN']);
                $entityManager->persist($user);
                $entityManager->flush();

                $this->addFlash('success', 'Modification du profil administrateur effectuée avec succès !');
            }

            return $this->render('admin/profil.html.twig', [
                'formAdmin' => $formAdmin,
                'admin' => $user,
            ]);
        }

        return $this->render('home/index.html.twig');
    }
}

templates/customer/profil.html.twig
{% extends 'base.html.twig' %}
{% import 'components/stepper.html.twig' as stepComponent %}


{% block title %}Modification du profil{% endblock %}

{% block body %}
    <!-- Conteneur principal pour les blocs -->
    {{ form_start(formCustomer) }} <!-- Déplacez form_start ici -->
    <div class="flex flex-col justify-center items-center mt-10">
        <div class="flex flex-row max-lg:flex-col justify-center items-start max-lg:items-center gap-10 w-full">
            <!-- Bloc de modification du profil -->
            <div class="min-w-72 w-1/3 w- bg-white p-6 rounded-lg shadow-md">
                <h1 class="text-2xl font-semibold text-primary-700 mb-4">Modifier le profil</h1>

                <div class="flex flex-col gap-4">
                    {{ form_row(formCustomer.name) }}
                    {{ form_row(formCustomer.surname) }}
                    {{ form_row(formCustomer.email) }}
                    {{ form_row(formCustomer.phone) }}
                    {{ form_row(formCustomer.plainPassword) }}
                </div>
            </div>

            <!-- Bloc de modification des adresses -->
            <div class="min-w-72 w-1/3 bg-white p-6 rounded-lg shadow-md">
                <h1 class="text-2xl font-semibold text-primary-700 mb-4">Gérer les adresses</h1>

                <div data-prototype="{{ form_widget(formCustomer.addresses.vars.prototype)|e }}" id="addresses-container" class="flex flex-col gap-4">
                    {% for address in formCustomer.addresses %}
                        <div class="address-card p-4 bg-gray-100 rounded-lg shadow-sm border border-gray-300">
                            <div class="flex justify-between items-center">
                                <h2 class="text-lg font-semibold text-primary-700">Adresse {{ loop.index }}</h2>
                                <div class="flex gap-2">
                                    <!-- Bouton Déplier/Plier -->
                                    <button type="button" class="toggle-btn text-primary-700 hover:text-primary-800 font-bold">
                                        Déplier
                                    </button>
                                    <!-- Bouton Supprimer -->
                                    <button type="button" class="remove-address-btn text-red-500 hover:text-red-700 font-bold">
                                        Supprimer
                                    </button>
                                </div>
                            </div>
                            <!-- Conteneur pliable -->
                            <div class="address-fields flex flex-col gap-2 mt-2 max-h-0 opacity-0 transition-all overflow-hidden">
                                {{ form_row(address.address, { 'label': 'Adresse' }) }}
                                {{ form_row(address.postalCode, { 'label': 'Code postal' }) }}
                                {{ form_row(address.city, { 'label': 'Ville' }) }}
                            </div>
                        </div>
                    {% endfor %}
                </div>

                <!-- Bouton pour ajouter une nouvelle adresse -->
                <button type="button" id="add-address-btn" class="mt-4 px-4 py-2 bg-primary-700 text-white rounded-lg hover:bg-primary-700">
                    Ajouter une adresse
                </button>
            </div>

        </div>

        <!-- Bouton de soumission -->
        <div class="mt-8 w-full flex justify-center">
            {{ form_start(formCustomer) }}
            <button type="submit" class="px-4 py-2 bg-success-600 text-white rounded-lg hover:bg-success-700">
                Mettre à jour
            </button>
        </div>
    </div>
    {{ form_end(formCustomer) }}
    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const addressesContainer = document.querySelector('#addresses-container');
            const addAddressButton = document.querySelector('#add-address-btn');

            // Récupération du prototype Symfony
            let index = addressesContainer.children.length; // Compte initial des adresses
            const prototype = addressesContainer.dataset.prototype;

            // Fonction pour ajouter les gestionnaires "Déplier/Plier"
            const initializeToggleButtons = () => {
                const toggleButtons = addressesContainer.querySelectorAll('.toggle-btn');
                toggleButtons.forEach((button) => {
                    button.removeEventListener('click', toggleHandler); // Supprimer l'ancien gestionnaire
                    button.addEventListener('click', toggleHandler);
                });
            };

            // Fonction pour gérer le pliage/dépliage
            const toggleHandler = (event) => {
                const button = event.target;
                const addressFields = button.closest('.address-card').querySelector('.address-fields');
                const isHidden = addressFields.classList.contains('max-h-0');

                // Toggle classes for show/hide
                addressFields.classList.toggle('max-h-0', !isHidden);
                addressFields.classList.toggle('opacity-0', !isHidden);
                addressFields.classList.toggle('max-h-full', isHidden);
                addressFields.classList.toggle('opacity-100', isHidden);

                // Change button text
                button.textContent = isHidden ? 'Plier' : 'Déplier';
            };

            // Ajouter une nouvelle adresse
            addAddressButton.addEventListener('click', () => {
                // Remplace "__name__" dans le prototype par l'index actuel
                const newForm = prototype.replace(/__name__/g, index);
                index++;

                // Crée un conteneur pour la nouvelle adresse
                const addressCard = document.createElement('div');
                addressCard.className = 'address-card p-4 bg-gray-100 rounded-lg shadow-sm border border-gray-300';
                addressCard.innerHTML = `
            <div class="flex justify-between items-center">
                <h2 class="text-lg font-semibold text-primary-700">Nouvelle adresse</h2>
                <button type="button" class="toggle-btn text-primary-700 hover:text-primary-800 font-bold">
                    Déplier
                </button>
                <button type="button" class="remove-address-btn text-red-500 hover:text-red-700 font-bold">
                    Supprimer
                </button>
            </div>
            <div class="address-fields flex flex-col gap-2 mt-2 max-h-0 opacity-0 transition-all overflow-hidden">
                ${newForm}
            </div>
        `;

                // Ajoute la carte au conteneur
                addressesContainer.appendChild(addressCard);

                // Ajouter les gestionnaires d'événements pour les nouveaux boutons
                initializeToggleButtons();
                initializeRemoveButtons(addressCard.querySelector('.remove-address-btn'));
            });

            // Supprimer une adresse
            const initializeRemoveButtons = (button) => {
                button.addEventListener('click', (e) => {
                    const addressCard = e.target.closest('.address-card');
                    addressCard.remove();
                });
            };

            // Initialisation des boutons existants
            document.querySelectorAll('.remove-address-btn').forEach((button) => {
                initializeRemoveButtons(button);
            });

            // Initialiser les boutons "Déplier/Plier"
            initializeToggleButtons();
        });


    </script>

{% endblock %}