src/Entity/Provider.php
<?php

namespace App\Entity;

use App\Repository\ProviderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProviderRepository::class)]
class Provider extends Account
{
    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $PriceFDP = null;

    /**
     * @var Collection<int, Product>
     */
    #[ORM\OneToMany(targetEntity: Product::class, mappedBy: 'provider')]
    private Collection $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getPriceFDP(): ?string
    {
        return $this->PriceFDP;
    }

    public function setPriceFDP(string $PriceFDP): static
    {
        $this->PriceFDP = $PriceFDP;

        return $this;
    }

    /**
     * @return Collection<int, Product>
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): static
    {
        if (!$this->products->contains($product)) {
            $this->products->add($product);
            $product->setProvider($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): static
    {
        if ($this->products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getProvider() === $this) {
                $product->setProvider(null);
            }
        }

        return $this;
    }
}

templates/provider/profil.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProviderController!{% endblock %}

{% block body %}
    {{ form_start(formProvider) }}
    <div class="flex flex-col justify-center items-center mt-10">
        <div class="flex flex-row max-lg:flex-col justify-center items-start max-lg:items-center gap-10 w-full">
            <!-- Bloc de modification du profil -->
            <div class="min-w-72 w-1/3 bg-white p-6 rounded-lg shadow-md">
                <h1 class="text-2xl font-semibold text-primary-700 mb-4">Modifier le profil</h1>

                <div class="flex flex-col gap-4">
                    {{ form_row(formProvider.name) }}
                    {{ form_row(formProvider.email) }}
                    {{ form_row(formProvider.phone) }}
                    {{ form_row(formProvider.plainPassword) }}
                    {{ form_row(formProvider.priceFDP) }}
                </div>
            </div>
        </div>

        <!-- Bouton de soumission -->
        <div class="mt-8 w-full flex justify-center">
            <button type="submit" class="px-4 py-2 bg-success-600 text-white rounded-lg hover:bg-success-700">
                Mettre à jour
            </button>
        </div>
    </div>
    {{ form_end(formProvider) }}
{% endblock %}